name = "Blackmage"
uuid = "94fbf62c-7f84-4dac-b8e8-d17b7072c94a"
authors = ["Dominik Bergermann <dominik.bergermann@rwth-aachen.de>"]
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
Distributions = "0.25.122"
LinearAlgebra = "1.11.0"
Plots = "1.41.1"
StaticArrays = "1.9.15"
