name = "Blackmage"
uuid = "94fbf62c-7f84-4dac-b8e8-d17b7072c94a"
authors = ["Dominik Bergermann <dominik.bergermann@rwth-aachen.de>"]
version = "0.1.0"

[deps]
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"
